<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-MV5SLF0" failures="2" tests="4" name="PetTests" time="14.191" errors="0" timestamp="2024-08-07T11:35:39 IST">
  <testcase classname="api.test.UserTests2" name="testpostUser" time="7.042"/>
  <testcase classname="api.test.UserTests2" name="testgetUser" time="1.253">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests2.testgetUser(UserTests2.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testgetUser -->
  <testcase classname="api.test.UserTests2" name="testupdateUser" time="2.35"/>
  <testcase classname="api.test.UserTests2" name="testdeletetUser" time="1.171">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests2.testdeletetUser(UserTests2.java:87)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testdeletetUser -->
</testsuite> <!-- PetTests -->
